# config/experiment_config.yaml
wandb:
  enabled: true
  project: "fspmi-report"
  entity: null
  tags: ["report", "racetrack"]

environment:
  name: "racetrack"
  params:
    initial_configuration: [0.5, 0.5, 0, 0]
    track_file: T1
    pfail: 0.07

model_chooser:
  type: "greedy"
  gp:
    beta: 2.0
    gp_update_frequency: 10
  greedy:
    do_not_create_transitions: true

output:
  dir: "./data/experiments"
  save_gp_metrics: true
  save_sapmi_metrics: false

experiments:
  standard_spmi:
    enabled: true
    max_iter: 1000


  federated_spmi:
    enabled: true
    configurations:
      - n_agents: 2
        episodes_per_round: 100
        max_rounds: 1000
      - n_agents: 2
        episodes_per_round: 200
        max_rounds: 1000
      - n_agents: 2
        episodes_per_round: 400
        max_rounds: 1000
      - n_agents: 2
        episodes_per_round: 800
        max_rounds: 1000

      - n_agents: 4
        episodes_per_round: 100
        max_rounds: 1000
      - n_agents: 4
        episodes_per_round: 200
        max_rounds: 1000
      - n_agents: 4
        episodes_per_round: 400
        max_rounds: 1000
      - n_agents: 4
        episodes_per_round: 800
        max_rounds: 1000

      - n_agents: 8
        episodes_per_round: 100
        max_rounds: 1000
      - n_agents: 8
        episodes_per_round: 200
        max_rounds: 1000
      - n_agents: 8
        episodes_per_round: 400
        max_rounds: 1000
      - n_agents: 8
        episodes_per_round: 800
        max_rounds: 1000

  